import = [
    "~/.config/alacritty/themes/themes/gruvbox_material_hard_dark.toml"
]
[window]
	opacity=0.95
  # blur = true 
[font]
	size=17.5
 
#adding new
[window.padding]
  x = 4
  y = 4

[mouse]
   hide_when_typing = true
